In [16]:
import numpy as np

In [17]:
tabel_1 = np.arange(0, 240, 1.8)
tabel_1 # สร้าง array tabel_1

array([   0. ,    1.8,    3.6,    5.4,    7.2,    9. ,   10.8,   12.6,
         14.4,   16.2,   18. ,   19.8,   21.6,   23.4,   25.2,   27. ,
         28.8,   30.6,   32.4,   34.2,   36. ,   37.8,   39.6,   41.4,
         43.2,   45. ,   46.8,   48.6,   50.4,   52.2,   54. ,   55.8,
         57.6,   59.4,   61.2,   63. ,   64.8,   66.6,   68.4,   70.2,
         72. ,   73.8,   75.6,   77.4,   79.2,   81. ,   82.8,   84.6,
         86.4,   88.2,   90. ,   91.8,   93.6,   95.4,   97.2,   99. ,
        100.8,  102.6,  104.4,  106.2,  108. ,  109.8,  111.6,  113.4,
        115.2,  117. ,  118.8,  120.6,  122.4,  124.2,  126. ,  127.8,
        129.6,  131.4,  133.2,  135. ,  136.8,  138.6,  140.4,  142.2,
        144. ,  145.8,  147.6,  149.4,  151.2,  153. ,  154.8,  156.6,
        158.4,  160.2,  162. ,  163.8,  165.6,  167.4,  169.2,  171. ,
        172.8,  174.6,  176.4,  178.2,  180. ,  181.8,  183.6,  185.4,
        187.2,  189. ,  190.8,  192.6,  194.4,  196.2,  198. ,  199.8,
      

In [18]:
add_0 = np.zeros(6)
add_0 # สร้าง 0

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
tabel_1 = np.append(add_0, tabel_1) # เพิ่ม 0 ให้ครบ 140

In [20]:
tabel_1[139] = 240 #แก้ 239.4 เป็น 240 
tabel_1

array([   0. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,    1.8,
          3.6,    5.4,    7.2,    9. ,   10.8,   12.6,   14.4,   16.2,
         18. ,   19.8,   21.6,   23.4,   25.2,   27. ,   28.8,   30.6,
         32.4,   34.2,   36. ,   37.8,   39.6,   41.4,   43.2,   45. ,
         46.8,   48.6,   50.4,   52.2,   54. ,   55.8,   57.6,   59.4,
         61.2,   63. ,   64.8,   66.6,   68.4,   70.2,   72. ,   73.8,
         75.6,   77.4,   79.2,   81. ,   82.8,   84.6,   86.4,   88.2,
         90. ,   91.8,   93.6,   95.4,   97.2,   99. ,  100.8,  102.6,
        104.4,  106.2,  108. ,  109.8,  111.6,  113.4,  115.2,  117. ,
        118.8,  120.6,  122.4,  124.2,  126. ,  127.8,  129.6,  131.4,
        133.2,  135. ,  136.8,  138.6,  140.4,  142.2,  144. ,  145.8,
        147.6,  149.4,  151.2,  153. ,  154.8,  156.6,  158.4,  160.2,
        162. ,  163.8,  165.6,  167.4,  169.2,  171. ,  172.8,  174.6,
        176.4,  178.2,  180. ,  181.8,  183.6,  185.4,  187.2,  189. ,
      

In [21]:
tabel_2 = np.arange(240 ,480 ,1.8)
tabel_2 # สร้าง array tabel_1

array([ 240. ,  241.8,  243.6,  245.4,  247.2,  249. ,  250.8,  252.6,
        254.4,  256.2,  258. ,  259.8,  261.6,  263.4,  265.2,  267. ,
        268.8,  270.6,  272.4,  274.2,  276. ,  277.8,  279.6,  281.4,
        283.2,  285. ,  286.8,  288.6,  290.4,  292.2,  294. ,  295.8,
        297.6,  299.4,  301.2,  303. ,  304.8,  306.6,  308.4,  310.2,
        312. ,  313.8,  315.6,  317.4,  319.2,  321. ,  322.8,  324.6,
        326.4,  328.2,  330. ,  331.8,  333.6,  335.4,  337.2,  339. ,
        340.8,  342.6,  344.4,  346.2,  348. ,  349.8,  351.6,  353.4,
        355.2,  357. ,  358.8,  360.6,  362.4,  364.2,  366. ,  367.8,
        369.6,  371.4,  373.2,  375. ,  376.8,  378.6,  380.4,  382.2,
        384. ,  385.8,  387.6,  389.4,  391.2,  393. ,  394.8,  396.6,
        398.4,  400.2,  402. ,  403.8,  405.6,  407.4,  409.2,  411. ,
        412.8,  414.6,  416.4,  418.2,  420. ,  421.8,  423.6,  425.4,
        427.2,  429. ,  430.8,  432.6,  434.4,  436.2,  438. ,  439.8,
      

In [22]:
add_480 = np.array([480, 480, 480, 480, 480, 480]) #สร้าง 480

In [23]:
tabel_2 = np.append(tabel_2, add_480)
tabel_2 # เพิ่ม 480 ให้ครบ 140

array([ 240. ,  241.8,  243.6,  245.4,  247.2,  249. ,  250.8,  252.6,
        254.4,  256.2,  258. ,  259.8,  261.6,  263.4,  265.2,  267. ,
        268.8,  270.6,  272.4,  274.2,  276. ,  277.8,  279.6,  281.4,
        283.2,  285. ,  286.8,  288.6,  290.4,  292.2,  294. ,  295.8,
        297.6,  299.4,  301.2,  303. ,  304.8,  306.6,  308.4,  310.2,
        312. ,  313.8,  315.6,  317.4,  319.2,  321. ,  322.8,  324.6,
        326.4,  328.2,  330. ,  331.8,  333.6,  335.4,  337.2,  339. ,
        340.8,  342.6,  344.4,  346.2,  348. ,  349.8,  351.6,  353.4,
        355.2,  357. ,  358.8,  360.6,  362.4,  364.2,  366. ,  367.8,
        369.6,  371.4,  373.2,  375. ,  376.8,  378.6,  380.4,  382.2,
        384. ,  385.8,  387.6,  389.4,  391.2,  393. ,  394.8,  396.6,
        398.4,  400.2,  402. ,  403.8,  405.6,  407.4,  409.2,  411. ,
        412.8,  414.6,  416.4,  418.2,  420. ,  421.8,  423.6,  425.4,
        427.2,  429. ,  430.8,  432.6,  434.4,  436.2,  438. ,  439.8,
      

In [25]:
tabel_2.shape = (14,10)
tabel_2

array([[ 240. ,  241.8,  243.6,  245.4,  247.2,  249. ,  250.8,  252.6,
         254.4,  256.2],
       [ 258. ,  259.8,  261.6,  263.4,  265.2,  267. ,  268.8,  270.6,
         272.4,  274.2],
       [ 276. ,  277.8,  279.6,  281.4,  283.2,  285. ,  286.8,  288.6,
         290.4,  292.2],
       [ 294. ,  295.8,  297.6,  299.4,  301.2,  303. ,  304.8,  306.6,
         308.4,  310.2],
       [ 312. ,  313.8,  315.6,  317.4,  319.2,  321. ,  322.8,  324.6,
         326.4,  328.2],
       [ 330. ,  331.8,  333.6,  335.4,  337.2,  339. ,  340.8,  342.6,
         344.4,  346.2],
       [ 348. ,  349.8,  351.6,  353.4,  355.2,  357. ,  358.8,  360.6,
         362.4,  364.2],
       [ 366. ,  367.8,  369.6,  371.4,  373.2,  375. ,  376.8,  378.6,
         380.4,  382.2],
       [ 384. ,  385.8,  387.6,  389.4,  391.2,  393. ,  394.8,  396.6,
         398.4,  400.2],
       [ 402. ,  403.8,  405.6,  407.4,  409.2,  411. ,  412.8,  414.6,
         416.4,  418.2],
       [ 420. ,  421.8,  423.6

In [26]:
table_test = tabel_2[0:1]
table_test

array([[ 240. ,  241.8,  243.6,  245.4,  247.2,  249. ,  250.8,  252.6,
         254.4,  256.2]])